# Generated by Django 4.1.7 on 2024-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='moneyhour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
