# Generated by Django 4.1.7 on 2024-09-22 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dailyreward_userdailyreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reward_date', models.DateField(blank=True, null=True)),
                ('consecutive_days', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyreward',
            name='reward_amount',
        ),
        migrations.AddField(
            model_name='dailyreward',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyreward',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreward',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserDailyReward',
        ),
    ]
