# Generated by Django 4.2.16 on 2024-09-29 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_stop_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
