version: '3.12'

services:
  postgres-db:
    restart: always
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: spark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111

  web:
    restart: always
    build:
      context: .
    container_name: cinema
    command: make migrations
    depends_on:
      - postgres-db
    env_file: .env
    volumes:
      - static_volume:/usr/src/sparkcoin/static/
      - media_volume:/usr/src/sparkcoin/media/

  nginx:
    restart: always
    build:
      context: ./docker/nginx/.
    container_name: nginx
    volumes:
      - static_volume:/usr/src/sparkcoin/static/
      - media_volume:/usr/src/sparkcoin/media/
    ports:
      - '443:443'

  telegram-bot:
    restart: always
    build:
      context: ./docker/tgbot/.
    container_name: telegram-bot
    env_file: .env
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: