# Generated by Django 4.1.7 on 2024-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksuser',
            name='status',
            field=models.CharField(choices=[('checked', 'Checked'), ('done', 'Done')], default='new', max_length=10),
        ),
    ]
